### ISSUE TITLE
Parameter properties

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#4]
### Code

```ts
class C {
    constructor(readonly x) {}
}
```

### Eslint

```json
{
  "accessibility": null,
  "decorators": [],
  "isReadonly": true,
  "parameter": {
    "name": "x",
    "type": "Identifier",
    "typeAnnotation": {
      "type": "TypeAnnotation",
      "typeAnnotation": {
        "type": "TSNumberKeyword",
      },
    },
  },
  "type": "TSParameterProperty"
}
```

(Resembles TypeScript's `ParameterDeclaration`)

### Babylon

```json
{
  "name": "x",
  "readonly": true,
  "type": "Identifier",
  "typeAnnotation": {
    "type": "TSNumberKeyword",
  }
}
```

(Resembles handling of type annotation)

**Comment by JamesHenry** [comment]
I definitely prefer your `"readonly": true` - it feels much more consistent with other boolean property names on ESTree nodes, such as `computed` etc.

I'm not sure if we actually need the `TSParameterProperty` wrapper here. It is simply falling through to our auto-conversion logic, and I think we should look to convert it in the same way as babylon here. I will make this one as an ESLint change.

@andy-ms How are you handling `accessibility` and parameter decorators here?

**Comment by soda0289** [comment]
I think one of the reasons we gave Parameter properties their own node type was to allow for eslint rules to easily identify them. For instance if we wanted a rule to deny their use it would be easy to create a node listener for `TSParameterProperty`. I don't mind changing it just giving some insight into the original decision.

**Comment by andy-ms** [comment]
In the babylon implementation `"accessibility"` also goes directly on the identifier, along with `"optional"`.

**Comment by soda0289** [comment]
I'm not really sure what works best. For instance with interface and class properties #13 `optional` and `computed` go on the Property and Property Signature node instead of the `Identifier` node. I think we should try to avoid having too many properties on the `Identifier` node but it might make it more consistent. I kind of feel like they should be on the parent node but that might not make sense in all cases.

**Comment by andy-ms** [comment]
I don't really care either way. In babel we will simply delete the "readonly" flag (or "accessibility", or both), or replace the TSParameterProperty with its child, so it's easy either way.

**Comment by soda0289** [comment]
If we could I'd like to avoid modifying the `Identifier` node since it is already defined by estree and babylon ast. The properties `typeAnnotation` and `optional` should be fine since those are used in many places and estree has defined `typeAnnotation` on `Identifier` already.

Adding `accessibility` and `readonly` to `TSParameterProperty` instead of `Identifier` feels better to me.

**Comment by andy-ms** [comment]
OK, done. Note that I am using "readonly" instead of "isReadonly" as mentioned above.

**Comment by andy-ms** [comment]
Also, it's easier for me if any decorators are attatched to the TSParameterProperty instead of the identifier. It would be wierd if the child node had content that came syntactically before its parent.

**Comment by JamesHenry** [comment]
https://github.com/eslint/typescript-eslint-parser/pull/285
