### ISSUE TITLE
Type arguments

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#5]
### Code

```ts
foo<T>();
```

### Eslint

```json
"typeParameters": {
  "params": [
    {
      "id": {
        "name": "T",
        "type": "Identifier",
      },
      "type": "GenericTypeAnnotation",
      "typeParameters": null,
    }
  ],
  "type": "TypeParameterInstantiation",
}
```

(Note: `id` isn't necessarily an identifier, may be any type.)

### Babylon

```json
"typeArguments": [
  {
    "type": "TSTypeReference",
    "typeName": {
      "name": "T",
      "type": "Identifier",
    }
  },
],
```

(Resembles TypeScript's `CallExpression`. Uses an array of types directly.)

Similar to #8.

**Comment by andy-ms** [comment]
In this and #8 and #18, there is a `GenericTypeAnnotation` node inserted. These are actual parameters (i.e., arguments), not formal parameters, so they can be any type (including a generic type, but they usually aren't). I'm OK with adding an intermediate `TypeParameterInstantiation` node in between the argument list and its parent (now grandparent), but introducing even further indirection via `GenericTypeAnnotation` seems wrong.

**Comment by soda0289** [comment]
I'm fine with this change.

**Comment by andy-ms** [comment]
I've changed the babylon implementation to use "TypeParameterInstantiation" like flow does, but I'd like to replace the "GenericTypeAnnotation" with just a plain type.

**Comment by soda0289** [comment]
I can see how using `GenericTypeAnnotation` with an `id` property doesn't make sense. I'm fine with changing it. `TSTypeReference` with `typeName` makes sense to me

**Comment by JamesHenry** [comment]
@andy-ms Looking into this for my own understanding, it seems that the only place Flow supports "type arguments" is within https://flow.org/en/docs/types/generics/#toc-parameterized-generics

I think we will have considered this Flow code from their docs (which is of course also valid TS):

```ts
type Item<T> = {
  prop: T,
}

let item: Item<string> = {
  prop: "value"
};
```

...when developing the ESLint AST. It matches pretty well to what we are doing at first glance:
http://astexplorer.net/#/gist/dce0549e6fb71908a0c62e1a83043d5f/d7e1d9449ab9c97ea9558a8c9de40fbfbc1ded7f

Flow always uses an array of `typeParameters` (even when used as "type arguments"), and differentiates using `TypeParameterInstantiation` vs `TypeParameterDeclaration`.

Based on a comparison of your latest commit on the `typescript` branch, you appear to still be using an array of `typeArguments ` within the AST generated from the above source, is that intentional?

I personally agree that `typeArguments` is a much more appropriate name, but I'm not sure if the divergence from Flow's precedent is worth it.

Am I right in summarising the two separate points as being:

1. Do we always use `typeParameters` and differentiate using `TypeParameterInstantiation` vs `TypeParameterDeclaration`? Or go for `typeArguments` when used as arguments, and `typeParameters` when used as parameters

2. Do we change `GenericTypeAnnotation` -> `id` to be `TSTypeReference` -> `typeName`? (I think we are all in favour of this change, as Flow is simply much more limited in its use cases here and the precedent doesn't give us what we need

**Comment by andy-ms** [comment]
See `test/fixtures/type-arguments/call` in my branch.
It has:
```json
"typeArguments": {
  "type": "TypeParameterInstantiation",
  "params": [
    {
      "type": "TSTypeReference",
      "typeName": {
        "type": "Identifier",
        "name": "T"
      }
    }
  ]
}
```

Eslint has:
```json
"typeParameters": {
  "type": "TypeParameterInstantiation",
  "params": [
    {
      "type": "GenericTypeAnnotation",
      "id": {
        "type": "Identifier",
        "name": "T"
      },
      "typeParameters": null
    }
  ]
}
```

I'll change `"typeArguments"` to `"typeParameters"`.
But using a `GenericTypeAnnotation` inside the type arguments (parameters) isn't correct since any arbitrary type should be acceptable at that position.

**Comment by JamesHenry** [comment]
Thanks, @andy-ms! I'll look into the change on my side tomorrow
